---
title: "Delay Generator Code"
output: html_notebook
---

This is code for programming the DG 645 delay generator.

```{r, include = FALSE, message = FALSE}
library(tidyverse)
```

## 2016 12 14 Ionization Delay Sweep

```{r}
step_increment <- c(rep(0, times = 50),
                    rep(c(1, rep(0, times = 4)), times = 10),
                    rep(c(1, rep(0, times = 4)), times = 49), 
                    rep(c(1, rep(0, times = 4)), times = 15))

delay_position <- c(rep(1e-5, times = 100), rep(1e-4, times = 245), rep(1e-3, times = 75))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/Delay_Stepper.csv", col_names = FALSE)

```

## 2017 02 12 MOT Turn Off Delay Sweep

```{r}
step_increment <- c(rep(0, times = 40),
                    rep(c(1, rep(0, times = 4)), times = 10),
                    rep(c(1, rep(0, times = 4)), times = 49))

delay_position <- c(rep(1e-4, times = 90), rep(1e-3, times = 245))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170212_MOT_Turn_Off.csv", col_names = FALSE)

```

## 2017 02 13 MOT Turn Off Delay Sweep Longer Times

```{r}
step_increment <- c(rep(0, times = 40),
                    rep(c(1, rep(0, times = 4)), times = 10),
                    rep(c(1, rep(0, times = 4)), times = 49))

delay_position <- c(rep(1e-3, times = 90), rep(1e-2, times = 245))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170213_MOT_Turn_Off.csv", col_names = FALSE)

```

```{r}
step_increment <- c(rep(0, times = 40),
                    rep(c(1, rep(0, times = 4)), times = 10),
                    rep(c(1, rep(0, times = 4)), times = 19))

delay_position <- c(rep(1e-3, times = 90), rep(1e-2, times = 95))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170213_MOT_Turn_Off_First_Half.csv", col_names = FALSE)

```

```{r}
step_increment <- c(rep(c(1, rep(0, times = 4)), times = 30))

delay_position <- c(rep(1e-2, times = 150))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170213_MOT_Turn_Off_Second_Half.csv", col_names = FALSE)

```

```{r}
step_increment <- c(rep(0, times = 40),
                    rep(c(2, rep(0, times = 4)), times = 5),
                    rep(c(2, rep(0, times = 4)), times = 25))

delay_position <- c(rep(1e-3, times = 65), rep(1e-2, times = 125))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170213_MOT_Turn_Off_2_step.csv", col_names = FALSE)

```

## 2017 02 14 MOT Turn Off Delay Sweep Longer Times


```{r}
step_increment <- c(rep(0, times = 40),
                    rep(c(2, rep(0, times = 4)), times = 10),
                    rep(c(1, rep(0, times = 4)), times = 13))

delay_position <- c(rep(1e-2, times = 90), 
                    rep(1e-1, times = 65))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170214_MOT_Turn_Off.csv", col_names = FALSE)

```

## 2017 02 15 MOT Turn On Delay Sweep

```{r}
step_increment <- c(rep(0, times = 40),
                    rep(c(1, rep(0, times = 4)), times = 10), 
                    rep(c(1, rep(0, times = 4)), times = 14), 
                    rep(c(2, rep(0, times = 4)), times = 5))

delay_position <- c(rep(1e-2, times = 90), 
                    rep(1e-1, times = 70), 
                    rep(1e-1, times = 25))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170215_MOT_Turn_On.csv", col_names = FALSE)

```

```{r}
step_increment <- c(rep(0, times = 40), 
                    rep(c(4, rep(0, times = 4)), times = 5),
                    rep(c(2, rep(0, times = 4)), times = 24))

delay_position <- c(rep(1e-2, times = 65), 
                    rep(1e-1, times = 120))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170215_MOT_Turn_On_Faster_Steps.csv", col_names = FALSE)

```

## 2017 02 16 MOT Rise Time with higher resolution

```{r}
step_increment <- c(rep(0, times = 40),
                    rep(c(2, rep(0, times = 4)), times = 15), 
                    rep(c(1, rep(0, times = 4)), times = 5))

delay_position <- c(rep(1e-2, times = 115), 
                    rep(1, times = 25))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170216_MOT_Turn_On.csv", col_names = FALSE)

```

```{r}
step_increment <- c(rep(0, times = 40),
                    rep(c(1, rep(0, times = 4)), times = 15), 
                    rep(c(1, rep(0, times = 4)), times = 5))

delay_position <- c(rep(1e-2, times = 115), 
                    rep(1, times = 25))

sum(step_increment * delay_position) * 1e3

index <- c(1:length(step_increment))

delay_frame <- tibble(Index = index,
                      Step_Increment = step_increment, 
                      Delay_Position = delay_position)

#write_csv(delay_frame, "Delay_Generator/Files/20170216_MOT_Turn_On_Higher_res.csv", col_names = FALSE)

```






